[package]
name = "protocol-handler"
version = "0.1.0"
authors = ["Aakash Gajjar <skyqutip@gmail.com>"]
edition = "2018"

[dependencies]
json = "0.11.14"

[dependencies.url]
git = "https://github.com/servo/rust-url"

[[bin]]
name = "protocol-handler"
path = "protocol-handler.rs"
